[package]
name = "anyrun-emoji"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [
    "cdylib",
] # Required to build a dynamic library that can be loaded by anyrun

[dependencies]
anyrun-plugin = { git = "https://github.com/Kirottu/anyrun" }
abi_stable = "0.11"

anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ron = "0.8"
parking_lot = "0.12.3"
nucleo = "0.5"
